---
# tasks file for virtualbox

- name: Add the Oracle APT key
  become: yes
  apt_key: 
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present

- name: Get the fingerprint and assert it is correct
  become: yes
  command: apt-key fingerprint 2980AECF
  register: fingerprint
- assert:
    that:
      - "'B9F8 D658 297A F3EF C18D  5CDF A2F6 83C5 2980 AECF' in fingerprint.stdout"

- name: Add virtualbox source list
  become: yes
  lineinfile: >
    line="deb [ arch=amd64,arm64 ] http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
    dest=/etc/apt/sources.list.d/virtualbox.list
    state=present
    create=yes

- name: Installing dependencies
  become: yes
  apt: pkg={{ item }} state=installed
  with_items:
  - dkms
  - build-essential
  - "linux-headers-{{ansible_kernel}}"

- name: Install VirtualBox
  become: yes
  apt: pkg=virtualbox-{{ virtualbox_version }} state=present update_cache=yes

# Further installation must be done manually
# Follow the steps here:
# https://askubuntu.com/questions/900118/vboxdrv-sh-failed-modprobe-vboxdrv-failed-please-use-dmesg-to-find-out-why
